### ISSUE TITLE
json-edit: "No module named builtins"

### ISSUE THREAD

**Issue by sgbeal** [adamlatchem/toolchest#1]
According to <https://www.intrepiduniverse.com/projects/jsonEditor.html>, all that's required to run `json-edit` after cloning the repo is:

    ./json-edit.py

That fails with:

    Traceback (most recent call last):
      File "./json-edit.py", line 4, in <module>
        from builtins import range
    ImportError: No module named builtins

This is Mint Linux 19.2 and `python --version` says `Python 2.7.15+`.

Running it with `python3` gives a different error:

    Traceback (most recent call last):
      File "json-edit.py", line 9, in <module>
        import GUIApplication
      File "/home/stephan/src/toolchest/GUIApplication.py", line 10, in <module>
        import tkinter
    ModuleNotFoundError: No module named 'tkinter'

which kind of implies that some tk/python library is needed. So... `apt install python-tk`, after which...

Nope. Same error.

**Comment by adamlatchem** [comment]
Hi @sgbeal please pull the latest code as I have redone the imports to work with python2 and 3. As you have realised python-tk is needed (or python3-tk if you are using python3). I've added a screencast to the webpage showing a working setup under linux. Let me know if the current code still causes you an issue.

**Comment by sgbeal** [comment]
That seems to have done it, but a new(?) problem was apparently introduced (or maybe it's been there all along?). When opening my first json file i get:

![image](https://user-images.githubusercontent.com/235303/67633797-ce45e680-f8b4-11e9-8397-23f9cb9addd6.png)

JSON conventionally uses UTF8, not ASCII. Indeed, this file contains `\u`-encoded sequences and the one it's choking on is apparently the (C) symbol:

```
    "copyright": "\u00a9GOBLINKO",
```

Version info:

```
env python --version
Python 2.7.15+
```

If, however, i explicitly run it with python3 (after installing `python3-tk`), it can read that file just fine, so this may simply be an unfortunate limitation of python2 (if so, feel free to close this, as it's resolved with regards to python3).

**Comment by adamlatchem** [comment]
Hi @sgbeal - thank you for pointing out this issue. You are right, I broke it in the last commit because I hoped (rather than researched) that unicode_literals would fix the str/unicode issue. It didn't so you can see I've now aliased str to unicode.

Note, the version of Tk you use also has to 'support' UTF-8 - please see [Unicode and UTF-8](https://wiki.tcl-lang.org/page/Unicode+and+UTF-8) for more on that - though if you have 8.1 or above you should be okay. I suspect (but don't know 😊) Mint 19 uses it. Funnily enough I was previously using Mint until a few weeks back when I switched to Ubuntu on my Intel desktop (for no particular reason).

Please let me know if you encounter further issues.
